const SHOPIFY_SHOP_NAME = "SHOPIFY_SHOP_NAME";
const SHOPIFY_API_PASSWORD = "SHOPIFY_API_PASSWORD";
const SHOPIFY_API_KEY = "SHOPIFY_API_KEY";
const SHOPIFY_SHARED_SECRET = "SHOPIFY_SHARED_SECRET";

export {
  SHOPIFY_API_KEY,
  SHOPIFY_API_PASSWORD,
  SHOPIFY_SHOP_NAME,
  SHOPIFY_SHARED_SECRET
}