const SHOPIFY_SHOP_NAME = "SHOPIFY_SHOP_NAME";
const SHOPIFY_API_PASSWORD = "SHOPIFY_API_PASSWORD";
const SHOPIFY_API_KEY = "SHOPIFY_API_KEY";
const SHOPIFY_WEBHOOK_VERIFY_TOKEN = "SHOPIFY_WEBHOOK_VERIFY_TOKEN";

export {
  SHOPIFY_API_KEY,
  SHOPIFY_API_PASSWORD,
  SHOPIFY_SHOP_NAME,
  SHOPIFY_WEBHOOK_VERIFY_TOKEN
}